### ISSUE TITLE
1.20 release notes are out of date

### ISSUE THREAD

**Issue by cjohnston1158** [charmed-kubernetes/kubernetes-docs#546] opened 2021-03-19 17:16 UTC
On the docs, if I click 1.20 under supported versions and then click Release Notes, it still shows 1.20 as the latest version of the charms. It also looks like the [components](https://ubuntu.com/kubernetes/docs/1.20/components) page doesn't show the newer versions of the charms.

**Comment by evilnick** [comment] 2021-06-14 09:59
There is usually a delay between the release and the published docs being updated.
The automatically generated part of the docs (the versions of charms and pretty much all of the components page) get generated when the new bundle is published. They go in this repo usually the same day but there can be a delay in them being published on ubuntu.com. I think we are reducing this time, but all of these docs will be moving to discourse at some point so the delay will be shorter - currently it is mostly caused by waiting for the PR to ubuntu.com to get merged and the site updated.

**Closed by evilnick** 2021-06-14 09:59 UTC
